export const HTTP_STATUS_CODES: { code: number; text: string; description: string }[] = [
  { code: 200, text: "OK", description: "The request succeeded." },
  { code: 201, text: "Created", description: "The request succeeded and a new resource was created." },
  { code: 204, text: "No Content", description: "The request succeeded but there's no content to return." },
  { code: 301, text: "Moved Permanently", description: "The resource has permanently moved to a new URL." },
  { code: 302, text: "Found", description: "The resource temporarily resides at a different URL." },
  { code: 304, text: "Not Modified", description: "The cached version is still valid; no need to re-fetch." },
  { code: 400, text: "Bad Request", description: "The server couldn't understand the request due to invalid syntax." },
  { code: 401, text: "Unauthorized", description: "Authentication is required and has failed or not been provided." },
  { code: 403, text: "Forbidden", description: "The server understood the request but refuses to authorize it." },
  { code: 404, text: "Not Found", description: "The server can't find the requested resource." },
  { code: 405, text: "Method Not Allowed", description: "The request method isn't supported for this resource." },
  { code: 409, text: "Conflict", description: "The request conflicts with the current state of the resource." },
  { code: 410, text: "Gone", description: "The resource is no longer available and won't be again." },
  { code: 422, text: "Unprocessable Entity", description: "The request was well-formed but contains semantic errors." },
  { code: 429, text: "Too Many Requests", description: "The user has sent too many requests in a given time." },
  { code: 500, text: "Internal Server Error", description: "The server encountered an unexpected condition." },
  { code: 501, text: "Not Implemented", description: "The server doesn't support the functionality required." },
  { code: 502, text: "Bad Gateway", description: "The server got an invalid response from an upstream server." },
  { code: 503, text: "Service Unavailable", description: "The server isn't ready to handle the request (overload/maintenance)." },
  { code: 504, text: "Gateway Timeout", description: "The upstream server failed to respond in time." },
];
