export const MIME_TYPES: { ext: string; type: string }[] = [
  { ext: ".html", type: "text/html" },
  { ext: ".css", type: "text/css" },
  { ext: ".js", type: "text/javascript" },
  { ext: ".json", type: "application/json" },
  { ext: ".xml", type: "application/xml" },
  { ext: ".pdf", type: "application/pdf" },
  { ext: ".zip", type: "application/zip" },
  { ext: ".txt", type: "text/plain" },
  { ext: ".csv", type: "text/csv" },
  { ext: ".png", type: "image/png" },
  { ext: ".jpg / .jpeg", type: "image/jpeg" },
  { ext: ".gif", type: "image/gif" },
  { ext: ".svg", type: "image/svg+xml" },
  { ext: ".webp", type: "image/webp" },
  { ext: ".ico", type: "image/x-icon" },
  { ext: ".mp3", type: "audio/mpeg" },
  { ext: ".wav", type: "audio/wav" },
  { ext: ".mp4", type: "video/mp4" },
  { ext: ".webm", type: "video/webm" },
  { ext: ".woff", type: "font/woff" },
  { ext: ".woff2", type: "font/woff2" },
  { ext: ".ttf", type: "font/ttf" },
  { ext: ".doc", type: "application/msword" },
  { ext: ".docx", type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
  { ext: ".xls", type: "application/vnd.ms-excel" },
  { ext: ".xlsx", type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
  { ext: ".ppt", type: "application/vnd.ms-powerpoint" },
  { ext: ".mp4v / .m4v", type: "video/x-m4v" },
  { ext: ".wasm", type: "application/wasm" },
  { ext: ".form-urlencoded", type: "application/x-www-form-urlencoded" },
  { ext: ".multipart", type: "multipart/form-data" },
];
