// AUTO-GENERATED by scripts/generate-tools-data.mjs — do not hand-edit.
// Source of truth: toolslist.md (structure) + TOOLS-CHECKLIST.md (tier/done status).
// Re-run: node scripts/generate-tools-data.mjs

export interface Tool {
  name: string;
  slug: string;
  tier: number;
  done: boolean;
}

export interface ToolCategory {
  name: string;
  slug: string;
  tools: Tool[];
}

export const TOOL_CATEGORIES: ToolCategory[] = [
  {
    "name": "PDF Tools",
    "slug": "pdf-tools",
    "tools": [
      {
        "name": "PDF Merge",
        "slug": "pdf-merge",
        "tier": 3,
        "done": true
      },
      {
        "name": "PDF Split",
        "slug": "pdf-split",
        "tier": 3,
        "done": true
      },
      {
        "name": "PDF Compress",
        "slug": "pdf-compress",
        "tier": 3,
        "done": true
      },
      {
        "name": "PDF to JPG",
        "slug": "pdf-to-jpg",
        "tier": 3,
        "done": true
      },
      {
        "name": "JPG to PDF",
        "slug": "jpg-to-pdf",
        "tier": 2,
        "done": true
      },
      {
        "name": "PDF Rotate",
        "slug": "pdf-rotate",
        "tier": 2,
        "done": true
      },
      {
        "name": "PDF Extract Pages",
        "slug": "pdf-extract-pages",
        "tier": 2,
        "done": true
      },
      {
        "name": "PDF Delete Pages",
        "slug": "pdf-delete-pages",
        "tier": 2,
        "done": true
      },
      {
        "name": "PDF Reorder Pages",
        "slug": "pdf-reorder-pages",
        "tier": 2,
        "done": true
      },
      {
        "name": "PDF Add Watermark",
        "slug": "pdf-add-watermark",
        "tier": 2,
        "done": true
      },
      {
        "name": "PDF Unlock",
        "slug": "pdf-unlock",
        "tier": 3,
        "done": true
      },
      {
        "name": "PDF Metadata Editor",
        "slug": "pdf-metadata-editor",
        "tier": 2,
        "done": true
      },
      {
        "name": "PDF Page Numbering",
        "slug": "pdf-page-numbering",
        "tier": 2,
        "done": true
      },
      {
        "name": "PDF to Text",
        "slug": "pdf-to-text",
        "tier": 2,
        "done": true
      },
      {
        "name": "PDF to Word",
        "slug": "pdf-to-word",
        "tier": 6,
        "done": true
      },
      {
        "name": "Word to PDF",
        "slug": "word-to-pdf",
        "tier": 5,
        "done": true
      },
      {
        "name": "PDF to Excel",
        "slug": "pdf-to-excel",
        "tier": 6,
        "done": true
      },
      {
        "name": "Excel to PDF",
        "slug": "excel-to-pdf",
        "tier": 5,
        "done": true
      },
      {
        "name": "PDF to PowerPoint",
        "slug": "pdf-to-powerpoint",
        "tier": 6,
        "done": true
      },
      {
        "name": "PowerPoint to PDF",
        "slug": "powerpoint-to-pdf",
        "tier": 5,
        "done": true
      },
      {
        "name": "PDF to PNG",
        "slug": "pdf-to-png",
        "tier": 3,
        "done": true
      },
      {
        "name": "PNG to PDF",
        "slug": "png-to-pdf",
        "tier": 2,
        "done": true
      },
      {
        "name": "PDF to HTML",
        "slug": "pdf-to-html",
        "tier": 5,
        "done": true
      },
      {
        "name": "HTML to PDF",
        "slug": "html-to-pdf",
        "tier": 3,
        "done": true
      },
      {
        "name": "PDF Editor",
        "slug": "pdf-editor",
        "tier": 1,
        "done": true
      },
      {
        "name": "PDF Signer (eSign PDF)",
        "slug": "pdf-signer",
        "tier": 4,
        "done": true
      },
      {
        "name": "PDF Form Filler",
        "slug": "pdf-form-filler",
        "tier": 4,
        "done": true
      },
      {
        "name": "PDF Compare",
        "slug": "pdf-compare",
        "tier": 4,
        "done": true
      },
      {
        "name": "PDF Repair",
        "slug": "pdf-repair",
        "tier": 5,
        "done": true
      },
      {
        "name": "PDF OCR",
        "slug": "pdf-ocr",
        "tier": 4,
        "done": true
      },
      {
        "name": "PDF to EPUB",
        "slug": "pdf-to-epub",
        "tier": 1,
        "done": true
      },
      {
        "name": "PDF Page Size Converter (A4/Letter/Legal)",
        "slug": "pdf-page-size-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "PDF Crop",
        "slug": "pdf-crop",
        "tier": 3,
        "done": true
      },
      {
        "name": "PDF Redact",
        "slug": "pdf-redact",
        "tier": 4,
        "done": true
      },
      {
        "name": "PDF Flatten",
        "slug": "pdf-flatten",
        "tier": 3,
        "done": true
      },
      {
        "name": "PDF Bookmark Editor",
        "slug": "pdf-bookmark-editor",
        "tier": 3,
        "done": true
      },
      {
        "name": "PDF Header & Footer Adder",
        "slug": "pdf-header-and-footer-adder",
        "tier": 2,
        "done": true
      },
      {
        "name": "PDF to CSV",
        "slug": "pdf-to-csv",
        "tier": 5,
        "done": true
      },
      {
        "name": "PDF Splitter by File Size",
        "slug": "pdf-splitter-by-file-size",
        "tier": 3,
        "done": true
      },
      {
        "name": "Scan to PDF",
        "slug": "scan-to-pdf",
        "tier": 3,
        "done": true
      },
      {
        "name": "PDF Reader Online",
        "slug": "pdf-reader-online",
        "tier": 2,
        "done": true
      },
      {
        "name": "PDF Annotator",
        "slug": "pdf-annotator",
        "tier": 4,
        "done": true
      },
      {
        "name": "PDF to Markdown",
        "slug": "pdf-to-markdown",
        "tier": 5,
        "done": true
      },
      {
        "name": "PDF Grayscale Converter",
        "slug": "pdf-grayscale-converter",
        "tier": 3,
        "done": true
      },
      {
        "name": "PDF Page Extractor to Images",
        "slug": "pdf-page-extractor-to-images",
        "tier": 3,
        "done": true
      },
      {
        "name": "PDF Protect",
        "slug": "pdf-protect",
        "tier": 4,
        "done": false
      }
    ]
  },
  {
    "name": "Image Tools",
    "slug": "image-tools",
    "tools": [
      {
        "name": "Image Compressor",
        "slug": "image-compressor",
        "tier": 2,
        "done": true
      },
      {
        "name": "Image Resizer",
        "slug": "image-resizer",
        "tier": 2,
        "done": true
      },
      {
        "name": "Crop Image",
        "slug": "crop-image",
        "tier": 2,
        "done": true
      },
      {
        "name": "Rotate Image",
        "slug": "rotate-image",
        "tier": 1,
        "done": true
      },
      {
        "name": "Flip Image",
        "slug": "flip-image",
        "tier": 1,
        "done": true
      },
      {
        "name": "PNG to JPG",
        "slug": "png-to-jpg",
        "tier": 1,
        "done": true
      },
      {
        "name": "JPG to PNG",
        "slug": "jpg-to-png",
        "tier": 1,
        "done": true
      },
      {
        "name": "WebP to JPG",
        "slug": "webp-to-jpg",
        "tier": 1,
        "done": true
      },
      {
        "name": "JPG to WebP",
        "slug": "jpg-to-webp",
        "tier": 1,
        "done": true
      },
      {
        "name": "AVIF to JPG",
        "slug": "avif-to-jpg",
        "tier": 2,
        "done": true
      },
      {
        "name": "SVG to PNG",
        "slug": "svg-to-png",
        "tier": 2,
        "done": true
      },
      {
        "name": "PNG to SVG",
        "slug": "png-to-svg",
        "tier": 4,
        "done": true
      },
      {
        "name": "Remove Background",
        "slug": "remove-background",
        "tier": 6,
        "done": true
      },
      {
        "name": "Blur Image",
        "slug": "blur-image",
        "tier": 1,
        "done": true
      },
      {
        "name": "Image Watermark",
        "slug": "image-watermark",
        "tier": 2,
        "done": true
      },
      {
        "name": "Image Color Picker",
        "slug": "image-color-picker",
        "tier": 1,
        "done": true
      },
      {
        "name": "Image Metadata Viewer",
        "slug": "image-metadata-viewer",
        "tier": 2,
        "done": true
      },
      {
        "name": "Image to Base64",
        "slug": "image-to-base64",
        "tier": 1,
        "done": true
      },
      {
        "name": "Base64 to Image",
        "slug": "base64-to-image",
        "tier": 1,
        "done": true
      },
      {
        "name": "Image DPI Converter",
        "slug": "image-dpi-converter",
        "tier": 2,
        "done": true
      },
      {
        "name": "Universal Image Converter",
        "slug": "universal-image-converter",
        "tier": 2,
        "done": true
      },
      {
        "name": "HEIC to JPG",
        "slug": "heic-to-jpg",
        "tier": 4,
        "done": true
      },
      {
        "name": "HEIC to PNG",
        "slug": "heic-to-png",
        "tier": 4,
        "done": true
      },
      {
        "name": "BMP to JPG",
        "slug": "bmp-to-jpg",
        "tier": 1,
        "done": true
      },
      {
        "name": "TIFF to JPG",
        "slug": "tiff-to-jpg",
        "tier": 3,
        "done": true
      },
      {
        "name": "GIF to PNG",
        "slug": "gif-to-png",
        "tier": 2,
        "done": true
      },
      {
        "name": "PNG to GIF",
        "slug": "png-to-gif",
        "tier": 2,
        "done": true
      },
      {
        "name": "ICO Converter (Favicon Maker)",
        "slug": "ico-converter",
        "tier": 2,
        "done": true
      },
      {
        "name": "Image to PDF",
        "slug": "image-to-pdf",
        "tier": 2,
        "done": true
      },
      {
        "name": "Image Splitter (Grid Cutter)",
        "slug": "image-splitter",
        "tier": 2,
        "done": true
      },
      {
        "name": "Image Collage Maker",
        "slug": "image-collage-maker",
        "tier": 3,
        "done": true
      },
      {
        "name": "Image Sharpener",
        "slug": "image-sharpener",
        "tier": 2,
        "done": true
      },
      {
        "name": "Image Grayscale Converter",
        "slug": "image-grayscale-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Image Rounded Corners",
        "slug": "image-rounded-corners",
        "tier": 1,
        "done": true
      },
      {
        "name": "Image Border Adder",
        "slug": "image-border-adder",
        "tier": 1,
        "done": true
      },
      {
        "name": "Meme Generator",
        "slug": "meme-generator",
        "tier": 2,
        "done": true
      },
      {
        "name": "Photo Filters",
        "slug": "photo-filters",
        "tier": 2,
        "done": true
      },
      {
        "name": "Image Compare (Diff Tool)",
        "slug": "image-compare",
        "tier": 3,
        "done": true
      },
      {
        "name": "Passport Photo Maker",
        "slug": "passport-photo-maker",
        "tier": 3,
        "done": true
      },
      {
        "name": "Image Pixelator",
        "slug": "image-pixelator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Favicon Generator",
        "slug": "favicon-generator",
        "tier": 2,
        "done": true
      },
      {
        "name": "Social Media Image Resizer",
        "slug": "social-media-image-resizer",
        "tier": 1,
        "done": true
      },
      {
        "name": "Image EXIF Remover",
        "slug": "image-exif-remover",
        "tier": 2,
        "done": true
      },
      {
        "name": "Image Noise Reducer",
        "slug": "image-noise-reducer",
        "tier": 3,
        "done": true
      },
      {
        "name": "Batch Image Resizer",
        "slug": "batch-image-resizer",
        "tier": 2,
        "done": true
      },
      {
        "name": "Image Rotator by Angle",
        "slug": "image-rotator-by-angle",
        "tier": 1,
        "done": true
      },
      {
        "name": "Transparent Background Maker",
        "slug": "transparent-background-maker",
        "tier": 6,
        "done": true
      },
      {
        "name": "JPG to HEIC",
        "slug": "jpg-to-heic",
        "tier": 4,
        "done": false
      },
      {
        "name": "AI Image Upscaler",
        "slug": "ai-image-upscaler",
        "tier": 6,
        "done": false
      }
    ]
  },
  {
    "name": "Text Tools",
    "slug": "text-tools",
    "tools": [
      {
        "name": "Word Counter",
        "slug": "word-counter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Character Counter",
        "slug": "character-counter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Case Converter",
        "slug": "case-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Remove Duplicate Lines",
        "slug": "remove-duplicate-lines",
        "tier": 1,
        "done": true
      },
      {
        "name": "Sort Lines",
        "slug": "sort-lines",
        "tier": 1,
        "done": true
      },
      {
        "name": "Text Reverser",
        "slug": "text-reverser",
        "tier": 1,
        "done": true
      },
      {
        "name": "Slug Generator",
        "slug": "slug-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Lorem Ipsum Generator",
        "slug": "lorem-ipsum-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Random Text Generator",
        "slug": "random-text-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Find & Replace",
        "slug": "find-and-replace",
        "tier": 1,
        "done": true
      },
      {
        "name": "Text Cleaner",
        "slug": "text-cleaner",
        "tier": 1,
        "done": true
      },
      {
        "name": "Remove Extra Spaces",
        "slug": "remove-extra-spaces",
        "tier": 1,
        "done": true
      },
      {
        "name": "URL Encoder",
        "slug": "url-encoder",
        "tier": 1,
        "done": true
      },
      {
        "name": "URL Decoder",
        "slug": "url-decoder",
        "tier": 1,
        "done": true
      },
      {
        "name": "Word Frequency Counter",
        "slug": "word-frequency-counter",
        "tier": 1,
        "done": true
      },
      {
        "name": "ROT13 Encoder",
        "slug": "rot13-encoder",
        "tier": 1,
        "done": true
      },
      {
        "name": "Morse Code Translator",
        "slug": "morse-code-translator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Binary to Text",
        "slug": "binary-to-text",
        "tier": 1,
        "done": true
      },
      {
        "name": "Text to Binary",
        "slug": "text-to-binary",
        "tier": 1,
        "done": true
      },
      {
        "name": "Palindrome Checker",
        "slug": "palindrome-checker",
        "tier": 1,
        "done": true
      },
      {
        "name": "Anagram Solver",
        "slug": "anagram-solver",
        "tier": 1,
        "done": true
      },
      {
        "name": "Line Counter",
        "slug": "line-counter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Paragraph Counter",
        "slug": "paragraph-counter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Whitespace Remover",
        "slug": "whitespace-remover",
        "tier": 1,
        "done": true
      },
      {
        "name": "Title Case Converter",
        "slug": "title-case-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Sentence Case Converter",
        "slug": "sentence-case-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Text to Hashtags Converter",
        "slug": "text-to-hashtags-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Fake Text / Placeholder Generator",
        "slug": "fake-text-placeholder-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Text Wrapper",
        "slug": "text-wrapper",
        "tier": 1,
        "done": true
      },
      {
        "name": "Column to Comma Converter",
        "slug": "column-to-comma-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Duplicate Word Remover",
        "slug": "duplicate-word-remover",
        "tier": 1,
        "done": true
      },
      {
        "name": "Text to Slug Bulk Converter",
        "slug": "text-to-slug-bulk-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Text Diff Checker",
        "slug": "text-diff-checker",
        "tier": 2,
        "done": false
      },
      {
        "name": "Text to Speech",
        "slug": "text-to-speech",
        "tier": 2,
        "done": false
      },
      {
        "name": "Speech to Text",
        "slug": "speech-to-text",
        "tier": 2,
        "done": false
      },
      {
        "name": "Text Encryptor / Decryptor",
        "slug": "text-encryptor-decryptor",
        "tier": 2,
        "done": false
      }
    ]
  },
  {
    "name": "Developer Tools",
    "slug": "developer-tools",
    "tools": [
      {
        "name": "JSON Formatter",
        "slug": "json-formatter",
        "tier": 1,
        "done": true
      },
      {
        "name": "JSON Validator",
        "slug": "json-validator",
        "tier": 1,
        "done": true
      },
      {
        "name": "JSON Minifier",
        "slug": "json-minifier",
        "tier": 1,
        "done": true
      },
      {
        "name": "JSON to CSV",
        "slug": "json-to-csv",
        "tier": 2,
        "done": true
      },
      {
        "name": "CSV to JSON",
        "slug": "csv-to-json",
        "tier": 2,
        "done": true
      },
      {
        "name": "XML Formatter",
        "slug": "xml-formatter",
        "tier": 2,
        "done": true
      },
      {
        "name": "XML to JSON",
        "slug": "xml-to-json",
        "tier": 2,
        "done": true
      },
      {
        "name": "YAML Formatter",
        "slug": "yaml-formatter",
        "tier": 2,
        "done": true
      },
      {
        "name": "YAML to JSON",
        "slug": "yaml-to-json",
        "tier": 2,
        "done": true
      },
      {
        "name": "JSON to YAML",
        "slug": "json-to-yaml",
        "tier": 2,
        "done": true
      },
      {
        "name": "Base64 Encode",
        "slug": "base64-encode",
        "tier": 1,
        "done": true
      },
      {
        "name": "Base64 Decode",
        "slug": "base64-decode",
        "tier": 1,
        "done": true
      },
      {
        "name": "JWT Decoder",
        "slug": "jwt-decoder",
        "tier": 1,
        "done": true
      },
      {
        "name": "JWT Generator",
        "slug": "jwt-generator",
        "tier": 2,
        "done": true
      },
      {
        "name": "Regex Tester",
        "slug": "regex-tester",
        "tier": 1,
        "done": true
      },
      {
        "name": "HTML Minifier",
        "slug": "html-minifier",
        "tier": 2,
        "done": true
      },
      {
        "name": "CSS Minifier",
        "slug": "css-minifier",
        "tier": 2,
        "done": true
      },
      {
        "name": "JS Minifier",
        "slug": "js-minifier",
        "tier": 3,
        "done": true
      },
      {
        "name": "UUID Generator",
        "slug": "uuid-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Hash Generator",
        "slug": "hash-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "SQL Formatter",
        "slug": "sql-formatter",
        "tier": 2,
        "done": true
      },
      {
        "name": "SQL Minifier",
        "slug": "sql-minifier",
        "tier": 2,
        "done": true
      },
      {
        "name": "Cron Expression Generator",
        "slug": "cron-expression-generator",
        "tier": 2,
        "done": true
      },
      {
        "name": "HTML Formatter / Beautifier",
        "slug": "html-formatter-beautifier",
        "tier": 2,
        "done": true
      },
      {
        "name": "HTML to Markdown",
        "slug": "html-to-markdown",
        "tier": 2,
        "done": true
      },
      {
        "name": "Markdown to HTML",
        "slug": "markdown-to-html",
        "tier": 2,
        "done": true
      },
      {
        "name": "Markdown Previewer",
        "slug": "markdown-previewer",
        "tier": 2,
        "done": true
      },
      {
        "name": "Code Diff Checker",
        "slug": "code-diff-checker",
        "tier": 2,
        "done": true
      },
      {
        "name": "Code Beautifier (universal)",
        "slug": "code-beautifier",
        "tier": 3,
        "done": true
      },
      {
        "name": "Timestamp Converter",
        "slug": "timestamp-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Epoch / Unix Time Converter",
        "slug": "epoch-unix-time-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Color Code Converter (HEX/RGB/HSL)",
        "slug": "color-code-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "JSON Diff Checker",
        "slug": "json-diff-checker",
        "tier": 2,
        "done": true
      },
      {
        "name": "JSON Path Tester",
        "slug": "json-path-tester",
        "tier": 2,
        "done": true
      },
      {
        "name": "GraphQL Query Formatter",
        "slug": "graphql-query-formatter",
        "tier": 2,
        "done": true
      },
      {
        "name": "URL Parser",
        "slug": "url-parser",
        "tier": 1,
        "done": true
      },
      {
        "name": "User Agent Parser",
        "slug": "user-agent-parser",
        "tier": 2,
        "done": true
      },
      {
        "name": "HTTP Status Code Lookup",
        "slug": "http-status-code-lookup",
        "tier": 1,
        "done": true
      },
      {
        "name": "MIME Type Lookup",
        "slug": "mime-type-lookup",
        "tier": 1,
        "done": true
      },
      {
        "name": "Curl Command Generator",
        "slug": "curl-command-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Base32 Encode / Decode",
        "slug": "base32-encode-decode",
        "tier": 1,
        "done": true
      },
      {
        "name": "ASCII Table Reference",
        "slug": "ascii-table-reference",
        "tier": 1,
        "done": true
      },
      {
        "name": "Unicode Converter",
        "slug": "unicode-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Slugify Tool",
        "slug": "slugify-tool",
        "tier": 1,
        "done": true
      },
      {
        "name": "Git Ignore Generator",
        "slug": "git-ignore-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Open Source License Generator",
        "slug": "open-source-license-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "API Response Formatter",
        "slug": "api-response-formatter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Number Base Converter (Bin/Oct/Dec/Hex)",
        "slug": "number-base-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Environment Variable (.env) to JSON Converter",
        "slug": "environment-variable-to-json-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Webhook Tester",
        "slug": "webhook-tester",
        "tier": 5,
        "done": false
      }
    ]
  },
  {
    "name": "Video Tools",
    "slug": "video-tools",
    "tools": [
      {
        "name": "MP4 to WebM",
        "slug": "mp4-to-webm",
        "tier": 4,
        "done": true
      },
      {
        "name": "WebM to MP4",
        "slug": "webm-to-mp4",
        "tier": 4,
        "done": true
      },
      {
        "name": "Video Compressor",
        "slug": "video-compressor",
        "tier": 4,
        "done": true
      },
      {
        "name": "Video Trimmer",
        "slug": "video-trimmer",
        "tier": 3,
        "done": true
      },
      {
        "name": "Extract Audio from Video",
        "slug": "extract-audio-from-video",
        "tier": 4,
        "done": true
      },
      {
        "name": "Video to GIF",
        "slug": "video-to-gif",
        "tier": 4,
        "done": true
      },
      {
        "name": "GIF to MP4",
        "slug": "gif-to-mp4",
        "tier": 4,
        "done": true
      },
      {
        "name": "Change Video Speed",
        "slug": "change-video-speed",
        "tier": 4,
        "done": true
      },
      {
        "name": "Mute Video",
        "slug": "mute-video",
        "tier": 3,
        "done": true
      },
      {
        "name": "Merge Videos",
        "slug": "merge-videos",
        "tier": 4,
        "done": true
      },
      {
        "name": "MP4 to MP3",
        "slug": "mp4-to-mp3",
        "tier": 4,
        "done": true
      },
      {
        "name": "Video to Audio Converter",
        "slug": "video-to-audio-converter",
        "tier": 4,
        "done": true
      },
      {
        "name": "Video Rotator",
        "slug": "video-rotator",
        "tier": 3,
        "done": true
      },
      {
        "name": "Video Cropper",
        "slug": "video-cropper",
        "tier": 4,
        "done": true
      },
      {
        "name": "Video Resizer",
        "slug": "video-resizer",
        "tier": 4,
        "done": true
      },
      {
        "name": "Add Subtitles to Video",
        "slug": "add-subtitles-to-video",
        "tier": 5,
        "done": true
      },
      {
        "name": "Video Watermark",
        "slug": "video-watermark",
        "tier": 4,
        "done": true
      },
      {
        "name": "Reverse Video",
        "slug": "reverse-video",
        "tier": 5,
        "done": true
      },
      {
        "name": "Screen Recorder",
        "slug": "screen-recorder",
        "tier": 2,
        "done": true
      },
      {
        "name": "Video Thumbnail Generator",
        "slug": "video-thumbnail-generator",
        "tier": 2,
        "done": true
      },
      {
        "name": "Video Frame Extractor",
        "slug": "video-frame-extractor",
        "tier": 3,
        "done": true
      },
      {
        "name": "Loop Video Maker",
        "slug": "loop-video-maker",
        "tier": 3,
        "done": true
      },
      {
        "name": "Video Compressor to Target Size",
        "slug": "video-compressor-to-target-size",
        "tier": 5,
        "done": true
      },
      {
        "name": "AVI to MP4",
        "slug": "avi-to-mp4",
        "tier": 4,
        "done": true
      },
      {
        "name": "MOV to MP4",
        "slug": "mov-to-mp4",
        "tier": 4,
        "done": true
      },
      {
        "name": "MKV to MP4",
        "slug": "mkv-to-mp4",
        "tier": 4,
        "done": true
      },
      {
        "name": "FLV to MP4",
        "slug": "flv-to-mp4",
        "tier": 4,
        "done": true
      },
      {
        "name": "Video Joiner by Timeline",
        "slug": "video-joiner-by-timeline",
        "tier": 5,
        "done": true
      },
      {
        "name": "Video Aspect Ratio Converter",
        "slug": "video-aspect-ratio-converter",
        "tier": 4,
        "done": true
      }
    ]
  },
  {
    "name": "Audio Tools",
    "slug": "audio-tools",
    "tools": [
      {
        "name": "MP3 Converter",
        "slug": "mp3-converter",
        "tier": 4,
        "done": true
      },
      {
        "name": "WAV Converter",
        "slug": "wav-converter",
        "tier": 2,
        "done": true
      },
      {
        "name": "Audio Compressor",
        "slug": "audio-compressor",
        "tier": 4,
        "done": true
      },
      {
        "name": "Audio Cutter",
        "slug": "audio-cutter",
        "tier": 2,
        "done": true
      },
      {
        "name": "Audio Joiner",
        "slug": "audio-joiner",
        "tier": 3,
        "done": true
      },
      {
        "name": "Change Audio Speed",
        "slug": "change-audio-speed",
        "tier": 3,
        "done": true
      },
      {
        "name": "Audio Volume Booster",
        "slug": "audio-volume-booster",
        "tier": 2,
        "done": true
      },
      {
        "name": "Audio Metadata Editor",
        "slug": "audio-metadata-editor",
        "tier": 3,
        "done": true
      },
      {
        "name": "MP3 to WAV",
        "slug": "mp3-to-wav",
        "tier": 3,
        "done": true
      },
      {
        "name": "WAV to MP3",
        "slug": "wav-to-mp3",
        "tier": 4,
        "done": true
      },
      {
        "name": "OGG Converter",
        "slug": "ogg-converter",
        "tier": 4,
        "done": true
      },
      {
        "name": "FLAC Converter",
        "slug": "flac-converter",
        "tier": 4,
        "done": true
      },
      {
        "name": "AAC Converter",
        "slug": "aac-converter",
        "tier": 4,
        "done": true
      },
      {
        "name": "Audio Merger",
        "slug": "audio-merger",
        "tier": 3,
        "done": true
      },
      {
        "name": "Audio Pitch Changer",
        "slug": "audio-pitch-changer",
        "tier": 4,
        "done": true
      },
      {
        "name": "Audio Normalizer",
        "slug": "audio-normalizer",
        "tier": 3,
        "done": true
      },
      {
        "name": "Audio Fade In/Out Editor",
        "slug": "audio-fade-in-out-editor",
        "tier": 2,
        "done": true
      },
      {
        "name": "Ringtone Maker",
        "slug": "ringtone-maker",
        "tier": 2,
        "done": true
      },
      {
        "name": "Voice Recorder Online",
        "slug": "voice-recorder-online",
        "tier": 1,
        "done": true
      },
      {
        "name": "Universal Audio Format Converter",
        "slug": "universal-audio-format-converter",
        "tier": 4,
        "done": true
      },
      {
        "name": "Podcast Trimmer",
        "slug": "podcast-trimmer",
        "tier": 2,
        "done": true
      },
      {
        "name": "Silence Remover (Audio)",
        "slug": "silence-remover",
        "tier": 1,
        "done": true
      },
      {
        "name": "Text to Speech Audio Exporter",
        "slug": "text-to-speech-audio-exporter",
        "tier": 3,
        "done": false
      }
    ]
  },
  {
    "name": "OCR Tools",
    "slug": "ocr-tools",
    "tools": [
      {
        "name": "Image to Text",
        "slug": "image-to-text",
        "tier": 3,
        "done": true
      },
      {
        "name": "PDF to Text OCR",
        "slug": "pdf-to-text-ocr",
        "tier": 4,
        "done": true
      },
      {
        "name": "Handwriting OCR",
        "slug": "handwriting-ocr",
        "tier": 6,
        "done": true
      },
      {
        "name": "Screenshot OCR",
        "slug": "screenshot-ocr",
        "tier": 3,
        "done": true
      },
      {
        "name": "Multi-language OCR",
        "slug": "multi-language-ocr",
        "tier": 3,
        "done": true
      },
      {
        "name": "Table OCR (Image to Excel)",
        "slug": "table-ocr",
        "tier": 6,
        "done": true
      },
      {
        "name": "Receipt OCR",
        "slug": "receipt-ocr",
        "tier": 6,
        "done": true
      },
      {
        "name": "ID Card OCR",
        "slug": "id-card-ocr",
        "tier": 6,
        "done": true
      },
      {
        "name": "License Plate OCR",
        "slug": "license-plate-ocr",
        "tier": 6,
        "done": true
      },
      {
        "name": "Business Card OCR (to vCard)",
        "slug": "business-card-ocr",
        "tier": 1,
        "done": true
      },
      {
        "name": "OCR to Word",
        "slug": "ocr-to-word",
        "tier": 4,
        "done": true
      },
      {
        "name": "OCR to PDF (Searchable PDF)",
        "slug": "ocr-to-pdf",
        "tier": 4,
        "done": true
      },
      {
        "name": "Batch OCR Processor",
        "slug": "batch-ocr-processor",
        "tier": 4,
        "done": true
      }
    ]
  },
  {
    "name": "Archive Tools",
    "slug": "archive-tools",
    "tools": [
      {
        "name": "ZIP Extractor",
        "slug": "zip-extractor",
        "tier": 2,
        "done": true
      },
      {
        "name": "ZIP Creator",
        "slug": "zip-creator",
        "tier": 2,
        "done": true
      },
      {
        "name": "TAR Extractor",
        "slug": "tar-extractor",
        "tier": 3,
        "done": true
      },
      {
        "name": "GZIP Extractor",
        "slug": "gzip-extractor",
        "tier": 2,
        "done": true
      },
      {
        "name": "7Z Extractor",
        "slug": "7z-extractor",
        "tier": 4,
        "done": true
      },
      {
        "name": "RAR Extractor",
        "slug": "rar-extractor",
        "tier": 1,
        "done": true
      },
      {
        "name": "ZIP Password Remover",
        "slug": "zip-password-remover",
        "tier": 3,
        "done": true
      },
      {
        "name": "ZIP Password Protector",
        "slug": "zip-password-protector",
        "tier": 3,
        "done": true
      },
      {
        "name": "Universal File Compressor",
        "slug": "universal-file-compressor",
        "tier": 3,
        "done": true
      },
      {
        "name": "Archive Format Converter",
        "slug": "archive-format-converter",
        "tier": 4,
        "done": true
      },
      {
        "name": "ISO Extractor",
        "slug": "iso-extractor",
        "tier": 4,
        "done": true
      },
      {
        "name": "TAR.GZ Creator",
        "slug": "tar-gz-creator",
        "tier": 3,
        "done": true
      },
      {
        "name": "Split Archive by Size",
        "slug": "split-archive-by-size",
        "tier": 3,
        "done": true
      }
    ]
  },
  {
    "name": "Calculators",
    "slug": "calculators",
    "tools": [
      {
        "name": "Age Calculator",
        "slug": "age-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Percentage Calculator",
        "slug": "percentage-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Discount Calculator",
        "slug": "discount-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "BMI Calculator",
        "slug": "bmi-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Date Calculator",
        "slug": "date-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Time Calculator",
        "slug": "time-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Time Duration Calculator",
        "slug": "time-duration-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Time Zone Converter",
        "slug": "time-zone-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Countdown Timer Generator",
        "slug": "countdown-timer-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Simple Interest Calculator",
        "slug": "simple-interest-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Compound Interest Calculator",
        "slug": "compound-interest-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Salary Calculator",
        "slug": "salary-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Tip Calculator",
        "slug": "tip-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Fuel Cost Calculator",
        "slug": "fuel-cost-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Grade Calculator",
        "slug": "grade-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "GPA Calculator",
        "slug": "gpa-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Ovulation Calculator",
        "slug": "ovulation-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Pregnancy Due Date Calculator",
        "slug": "pregnancy-due-date-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Retirement Calculator",
        "slug": "retirement-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Random Number Range Calculator",
        "slug": "random-number-range-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Statistics Calculator (Mean/Median/Mode)",
        "slug": "statistics-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Standard Deviation Calculator",
        "slug": "standard-deviation-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Fraction Calculator",
        "slug": "fraction-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Ratio Calculator",
        "slug": "ratio-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Scientific Calculator",
        "slug": "scientific-calculator",
        "tier": 1,
        "done": true
      }
    ]
  },
  {
    "name": "Finance & Business Calculators",
    "slug": "finance-and-business-calculators",
    "tools": [
      {
        "name": "EMI Calculator",
        "slug": "emi-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "GST Calculator",
        "slug": "gst-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "SIP Calculator",
        "slug": "sip-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Loan Calculator",
        "slug": "loan-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Mortgage Calculator",
        "slug": "mortgage-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Loan Amortization Calculator",
        "slug": "loan-amortization-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Break-Even Calculator",
        "slug": "break-even-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Profit Margin Calculator",
        "slug": "profit-margin-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "ROI Calculator",
        "slug": "roi-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Tax Calculator",
        "slug": "tax-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "VAT Calculator",
        "slug": "vat-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Payroll Calculator",
        "slug": "payroll-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Invoice Generator",
        "slug": "invoice-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Freelance Rate Calculator",
        "slug": "freelance-rate-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Business Loan Calculator",
        "slug": "business-loan-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Depreciation Calculator",
        "slug": "depreciation-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Markup Calculator",
        "slug": "markup-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Net Worth Calculator",
        "slug": "net-worth-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Inflation Calculator",
        "slug": "inflation-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Savings Goal Calculator",
        "slug": "savings-goal-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Currency Converter",
        "slug": "currency-converter",
        "tier": 5,
        "done": false
      }
    ]
  },
  {
    "name": "Health & Fitness Calculators",
    "slug": "health-and-fitness-calculators",
    "tools": [
      {
        "name": "BMR Calculator",
        "slug": "bmr-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Body Fat Percentage Calculator",
        "slug": "body-fat-percentage-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Calorie Calculator",
        "slug": "calorie-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Ideal Weight Calculator",
        "slug": "ideal-weight-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Water Intake Calculator",
        "slug": "water-intake-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Heart Rate Zone Calculator",
        "slug": "heart-rate-zone-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Macro Calculator",
        "slug": "macro-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Waist-to-Hip Ratio Calculator",
        "slug": "waist-to-hip-ratio-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "One Rep Max Calculator",
        "slug": "one-rep-max-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Steps to Calories Calculator",
        "slug": "steps-to-calories-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Pace & Running Speed Calculator",
        "slug": "pace-and-running-speed-calculator",
        "tier": 1,
        "done": true
      }
    ]
  },
  {
    "name": "Unit & Measurement Converters",
    "slug": "unit-and-measurement-converters",
    "tools": [
      {
        "name": "Length Converter",
        "slug": "length-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Weight Converter",
        "slug": "weight-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Temperature Converter",
        "slug": "temperature-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Speed Converter",
        "slug": "speed-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Area Converter",
        "slug": "area-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Volume Converter",
        "slug": "volume-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Data Storage Converter (MB/GB/TB)",
        "slug": "data-storage-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Time Unit Converter",
        "slug": "time-unit-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Pressure Converter",
        "slug": "pressure-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Energy Converter",
        "slug": "energy-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Power Converter",
        "slug": "power-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Angle Converter",
        "slug": "angle-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Fuel Consumption Converter",
        "slug": "fuel-consumption-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Cooking Measurement Converter",
        "slug": "cooking-measurement-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Shoe Size Converter",
        "slug": "shoe-size-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Clothing Size Converter",
        "slug": "clothing-size-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Roman Numeral Converter",
        "slug": "roman-numeral-converter",
        "tier": 1,
        "done": true
      }
    ]
  },
  {
    "name": "AI Tools",
    "slug": "ai-tools",
    "tools": [
      {
        "name": "AI Keyword Extractor",
        "slug": "ai-keyword-extractor",
        "tier": 1,
        "done": true
      },
      {
        "name": "AI Resume Builder",
        "slug": "ai-resume-builder",
        "tier": 1,
        "done": true
      },
      {
        "name": "AI Business Name Generator",
        "slug": "ai-business-name-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "AI Background Remover",
        "slug": "ai-background-remover",
        "tier": 6,
        "done": false
      },
      {
        "name": "AI Image Caption Generator",
        "slug": "ai-image-caption-generator",
        "tier": 6,
        "done": false
      },
      {
        "name": "AI OCR Enhancer",
        "slug": "ai-ocr-enhancer",
        "tier": 6,
        "done": false
      },
      {
        "name": "AI Text Summarizer",
        "slug": "ai-text-summarizer",
        "tier": 6,
        "done": false
      },
      {
        "name": "AI Grammar Fixer",
        "slug": "ai-grammar-fixer",
        "tier": 6,
        "done": false
      },
      {
        "name": "AI Paraphraser",
        "slug": "ai-paraphraser",
        "tier": 6,
        "done": false
      },
      {
        "name": "AI Text Generator",
        "slug": "ai-text-generator",
        "tier": 6,
        "done": false
      },
      {
        "name": "AI Cover Letter Generator",
        "slug": "ai-cover-letter-generator",
        "tier": 6,
        "done": false
      },
      {
        "name": "AI Blog Idea Generator",
        "slug": "ai-blog-idea-generator",
        "tier": 6,
        "done": false
      },
      {
        "name": "AI Email Writer",
        "slug": "ai-email-writer",
        "tier": 6,
        "done": false
      },
      {
        "name": "AI Chatbot Reply Generator",
        "slug": "ai-chatbot-reply-generator",
        "tier": 6,
        "done": false
      },
      {
        "name": "AI Story Generator",
        "slug": "ai-story-generator",
        "tier": 6,
        "done": false
      },
      {
        "name": "AI Code Explainer",
        "slug": "ai-code-explainer",
        "tier": 6,
        "done": false
      },
      {
        "name": "AI SQL Query Generator",
        "slug": "ai-sql-query-generator",
        "tier": 6,
        "done": false
      },
      {
        "name": "AI Product Description Generator",
        "slug": "ai-product-description-generator",
        "tier": 6,
        "done": false
      },
      {
        "name": "AI Headline Generator",
        "slug": "ai-headline-generator",
        "tier": 6,
        "done": false
      },
      {
        "name": "AI Title Generator",
        "slug": "ai-title-generator",
        "tier": 6,
        "done": false
      },
      {
        "name": "AI Slogan Generator",
        "slug": "ai-slogan-generator",
        "tier": 6,
        "done": false
      },
      {
        "name": "AI Image Generator",
        "slug": "ai-image-generator",
        "tier": 6,
        "done": false
      },
      {
        "name": "AI Voice Generator",
        "slug": "ai-voice-generator",
        "tier": 6,
        "done": false
      },
      {
        "name": "AI Translator",
        "slug": "ai-translator",
        "tier": 1,
        "done": false
      },
      {
        "name": "AI PDF Summarizer",
        "slug": "ai-pdf-summarizer",
        "tier": 6,
        "done": false
      },
      {
        "name": "AI Resume Reviewer",
        "slug": "ai-resume-reviewer",
        "tier": 6,
        "done": false
      },
      {
        "name": "AI Content Detector",
        "slug": "ai-content-detector",
        "tier": 6,
        "done": false
      }
    ]
  },
  {
    "name": "Social Media Tools",
    "slug": "social-media-tools",
    "tools": [
      {
        "name": "Instagram Story Size Guide",
        "slug": "instagram-story-size-guide",
        "tier": 1,
        "done": true
      },
      {
        "name": "LinkedIn Post Formatter",
        "slug": "linkedin-post-formatter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Twitter/X Character Counter",
        "slug": "twitter-x-character-counter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Emoji Picker & Copy Tool",
        "slug": "emoji-picker-and-copy-tool",
        "tier": 1,
        "done": true
      },
      {
        "name": "Social Media Image Size Guide",
        "slug": "social-media-image-size-guide",
        "tier": 1,
        "done": true
      },
      {
        "name": "YouTube Thumbnail Downloader",
        "slug": "youtube-thumbnail-downloader",
        "tier": 2,
        "done": false
      },
      {
        "name": "YouTube Tags Extractor",
        "slug": "youtube-tags-extractor",
        "tier": 5,
        "done": false
      },
      {
        "name": "YouTube Title Generator",
        "slug": "youtube-title-generator",
        "tier": 3,
        "done": false
      },
      {
        "name": "YouTube Description Generator",
        "slug": "youtube-description-generator",
        "tier": 3,
        "done": false
      },
      {
        "name": "YouTube Video Downloader",
        "slug": "youtube-video-downloader",
        "tier": 6,
        "done": false
      },
      {
        "name": "YouTube Shorts Downloader",
        "slug": "youtube-shorts-downloader",
        "tier": 6,
        "done": false
      },
      {
        "name": "YouTube Channel ID Finder",
        "slug": "youtube-channel-id-finder",
        "tier": 5,
        "done": false
      },
      {
        "name": "Hashtag Generator",
        "slug": "hashtag-generator",
        "tier": 2,
        "done": false
      },
      {
        "name": "Instagram Caption Generator",
        "slug": "instagram-caption-generator",
        "tier": 2,
        "done": false
      },
      {
        "name": "Instagram Reels Downloader",
        "slug": "instagram-reels-downloader",
        "tier": 6,
        "done": false
      },
      {
        "name": "TikTok Video Downloader",
        "slug": "tiktok-video-downloader",
        "tier": 6,
        "done": false
      },
      {
        "name": "Facebook Video Downloader",
        "slug": "facebook-video-downloader",
        "tier": 6,
        "done": false
      },
      {
        "name": "Twitter/X Video Downloader",
        "slug": "twitter-x-video-downloader",
        "tier": 6,
        "done": false
      },
      {
        "name": "Pinterest Image Downloader",
        "slug": "pinterest-image-downloader",
        "tier": 5,
        "done": false
      },
      {
        "name": "Bio Link Page Generator",
        "slug": "bio-link-page-generator",
        "tier": 5,
        "done": false
      }
    ]
  },
  {
    "name": "SEO Tools",
    "slug": "seo-tools",
    "tools": [
      {
        "name": "Meta Tag Generator",
        "slug": "meta-tag-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Robots.txt Generator",
        "slug": "robots-txt-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Keyword Density Checker",
        "slug": "keyword-density-checker",
        "tier": 1,
        "done": true
      },
      {
        "name": "Open Graph Generator",
        "slug": "open-graph-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "SERP Snippet Preview Tool",
        "slug": "serp-snippet-preview-tool",
        "tier": 1,
        "done": true
      },
      {
        "name": "Sitemap Generator",
        "slug": "sitemap-generator",
        "tier": 3,
        "done": false
      },
      {
        "name": "Schema Markup Generator",
        "slug": "schema-markup-generator",
        "tier": 3,
        "done": false
      },
      {
        "name": "Backlink Checker",
        "slug": "backlink-checker",
        "tier": 6,
        "done": false
      },
      {
        "name": "Keyword Position Tracker",
        "slug": "keyword-position-tracker",
        "tier": 6,
        "done": false
      },
      {
        "name": "Page Speed Checker",
        "slug": "page-speed-checker",
        "tier": 5,
        "done": false
      },
      {
        "name": "Broken Link Checker",
        "slug": "broken-link-checker",
        "tier": 5,
        "done": false
      },
      {
        "name": "Domain Authority Checker",
        "slug": "domain-authority-checker",
        "tier": 6,
        "done": false
      },
      {
        "name": "XML Sitemap Validator",
        "slug": "xml-sitemap-validator",
        "tier": 3,
        "done": false
      },
      {
        "name": "Canonical Tag Checker",
        "slug": "canonical-tag-checker",
        "tier": 4,
        "done": false
      },
      {
        "name": "Google Cache Checker",
        "slug": "google-cache-checker",
        "tier": 5,
        "done": false
      },
      {
        "name": "Alt Text Checker",
        "slug": "alt-text-checker",
        "tier": 4,
        "done": false
      },
      {
        "name": "Header Tag (H1-H6) Analyzer",
        "slug": "header-tag-analyzer",
        "tier": 4,
        "done": false
      },
      {
        "name": "Readability Checker",
        "slug": "readability-checker",
        "tier": 3,
        "done": false
      },
      {
        "name": "Redirect Checker",
        "slug": "redirect-checker",
        "tier": 4,
        "done": false
      },
      {
        "name": "SSL Checker",
        "slug": "ssl-checker",
        "tier": 5,
        "done": false
      },
      {
        "name": "Mobile-Friendly Test",
        "slug": "mobile-friendly-test",
        "tier": 5,
        "done": false
      },
      {
        "name": "Domain Age Checker",
        "slug": "domain-age-checker",
        "tier": 5,
        "done": false
      }
    ]
  },
  {
    "name": "Security Tools",
    "slug": "security-tools",
    "tools": [
      {
        "name": "Password Generator",
        "slug": "password-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Password Strength Checker",
        "slug": "password-strength-checker",
        "tier": 2,
        "done": true
      },
      {
        "name": "SHA256 Generator",
        "slug": "sha256-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "MD5 Generator",
        "slug": "md5-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "HMAC Generator",
        "slug": "hmac-generator",
        "tier": 2,
        "done": true
      },
      {
        "name": "File Hash Checker",
        "slug": "file-hash-checker",
        "tier": 2,
        "done": true
      },
      {
        "name": "Two-Factor Backup Code Generator",
        "slug": "two-factor-backup-code-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "AES Encryption Tool",
        "slug": "aes-encryption-tool",
        "tier": 2,
        "done": true
      },
      {
        "name": "AES Decryption Tool",
        "slug": "aes-decryption-tool",
        "tier": 2,
        "done": true
      },
      {
        "name": "PGP Key Pair Generator",
        "slug": "pgp-key-pair-generator",
        "tier": 3,
        "done": true
      },
      {
        "name": "SSL Certificate Decoder",
        "slug": "ssl-certificate-decoder",
        "tier": 3,
        "done": true
      },
      {
        "name": "IP Blacklist Checker",
        "slug": "ip-blacklist-checker",
        "tier": 5,
        "done": true
      },
      {
        "name": "Data Breach Email Checker",
        "slug": "data-breach-email-checker",
        "tier": 5,
        "done": true
      },
      {
        "name": "CSRF Token Generator",
        "slug": "csrf-token-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Passphrase Generator",
        "slug": "passphrase-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "File Encryptor / Decryptor",
        "slug": "file-encryptor-decryptor",
        "tier": 2,
        "done": true
      },
      {
        "name": "Self-Destructing Secure Note Generator",
        "slug": "self-destructing-secure-note-generator",
        "tier": 5,
        "done": true
      }
    ]
  },
  {
    "name": "Document & Office Tools",
    "slug": "document-and-office-tools",
    "tools": [
      {
        "name": "CSV to Excel",
        "slug": "csv-to-excel",
        "tier": 3,
        "done": false
      },
      {
        "name": "Excel to CSV",
        "slug": "excel-to-csv",
        "tier": 2,
        "done": false
      },
      {
        "name": "DOCX to TXT",
        "slug": "docx-to-txt",
        "tier": 3,
        "done": false
      },
      {
        "name": "TXT to DOCX",
        "slug": "txt-to-docx",
        "tier": 2,
        "done": false
      },
      {
        "name": "ODT Converter",
        "slug": "odt-converter",
        "tier": 5,
        "done": false
      },
      {
        "name": "EPUB Converter",
        "slug": "epub-converter",
        "tier": 5,
        "done": false
      },
      {
        "name": "Document Merger",
        "slug": "document-merger",
        "tier": 4,
        "done": false
      },
      {
        "name": "Resume Builder",
        "slug": "resume-builder",
        "tier": 2,
        "done": false
      },
      {
        "name": "Cover Letter Generator",
        "slug": "cover-letter-generator",
        "tier": 2,
        "done": false
      },
      {
        "name": "Invoice Template Generator",
        "slug": "invoice-template-generator",
        "tier": 2,
        "done": false
      },
      {
        "name": "Certificate Generator",
        "slug": "certificate-generator",
        "tier": 2,
        "done": false
      },
      {
        "name": "Letterhead Generator",
        "slug": "letterhead-generator",
        "tier": 2,
        "done": false
      },
      {
        "name": "Business Card Designer",
        "slug": "business-card-designer",
        "tier": 3,
        "done": false
      }
    ]
  },
  {
    "name": "Spreadsheet & Data Tools",
    "slug": "spreadsheet-and-data-tools",
    "tools": [
      {
        "name": "CSV Viewer",
        "slug": "csv-viewer",
        "tier": 1,
        "done": true
      },
      {
        "name": "VLOOKUP Formula Generator",
        "slug": "vlookup-formula-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "CSV Merger",
        "slug": "csv-merger",
        "tier": 2,
        "done": false
      },
      {
        "name": "CSV Splitter",
        "slug": "csv-splitter",
        "tier": 2,
        "done": false
      },
      {
        "name": "Excel to JSON",
        "slug": "excel-to-json",
        "tier": 2,
        "done": false
      },
      {
        "name": "JSON to Excel",
        "slug": "json-to-excel",
        "tier": 2,
        "done": false
      },
      {
        "name": "Duplicate Row Remover",
        "slug": "duplicate-row-remover",
        "tier": 2,
        "done": false
      },
      {
        "name": "Data Cleaner",
        "slug": "data-cleaner",
        "tier": 3,
        "done": false
      },
      {
        "name": "Pivot Table Generator",
        "slug": "pivot-table-generator",
        "tier": 4,
        "done": false
      },
      {
        "name": "Chart Generator from CSV",
        "slug": "chart-generator-from-csv",
        "tier": 2,
        "done": false
      },
      {
        "name": "Excel Formula Generator",
        "slug": "excel-formula-generator",
        "tier": 2,
        "done": false
      }
    ]
  },
  {
    "name": "Color Tools",
    "slug": "color-tools",
    "tools": [
      {
        "name": "Color Picker",
        "slug": "color-picker",
        "tier": 1,
        "done": true
      },
      {
        "name": "HEX to RGB Converter",
        "slug": "hex-to-rgb-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "RGB to HEX Converter",
        "slug": "rgb-to-hex-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "HEX to HSL Converter",
        "slug": "hex-to-hsl-converter",
        "tier": 1,
        "done": true
      },
      {
        "name": "Gradient Generator",
        "slug": "gradient-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Color Contrast Checker",
        "slug": "color-contrast-checker",
        "tier": 1,
        "done": true
      },
      {
        "name": "Color Name Finder",
        "slug": "color-name-finder",
        "tier": 1,
        "done": true
      },
      {
        "name": "Random Color Generator",
        "slug": "random-color-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "CSS Gradient Generator",
        "slug": "css-gradient-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Tailwind Color Shade Generator",
        "slug": "tailwind-color-shade-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Color Palette Generator",
        "slug": "color-palette-generator",
        "tier": 2,
        "done": false
      },
      {
        "name": "Color Blindness Simulator",
        "slug": "color-blindness-simulator",
        "tier": 2,
        "done": false
      },
      {
        "name": "Image Color Palette Extractor",
        "slug": "image-color-palette-extractor",
        "tier": 2,
        "done": false
      }
    ]
  },
  {
    "name": "QR Code & Barcode Tools",
    "slug": "qr-code-and-barcode-tools",
    "tools": [
      {
        "name": "QR Code Generator",
        "slug": "qr-code-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "WiFi QR Code Generator",
        "slug": "wifi-qr-code-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "vCard QR Code Generator",
        "slug": "vcard-qr-code-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Barcode Generator",
        "slug": "barcode-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "UPC/EAN Generator",
        "slug": "upc-ean-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "QR Code Scanner",
        "slug": "qr-code-scanner",
        "tier": 2,
        "done": false
      },
      {
        "name": "Barcode Scanner",
        "slug": "barcode-scanner",
        "tier": 2,
        "done": false
      },
      {
        "name": "QR Code with Logo Generator",
        "slug": "qr-code-with-logo-generator",
        "tier": 2,
        "done": false
      },
      {
        "name": "Bulk QR Code Generator",
        "slug": "bulk-qr-code-generator",
        "tier": 2,
        "done": false
      }
    ]
  },
  {
    "name": "Random Generators",
    "slug": "random-generators",
    "tools": [
      {
        "name": "Random Number Generator",
        "slug": "random-number-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Random Name Generator",
        "slug": "random-name-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Random Word Generator",
        "slug": "random-word-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Random Sentence Generator",
        "slug": "random-sentence-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Coin Flip",
        "slug": "coin-flip",
        "tier": 1,
        "done": true
      },
      {
        "name": "Dice Roller",
        "slug": "dice-roller",
        "tier": 1,
        "done": true
      },
      {
        "name": "Random Date Generator",
        "slug": "random-date-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Random Team Generator",
        "slug": "random-team-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Yes/No Decision Maker",
        "slug": "yes-no-decision-maker",
        "tier": 1,
        "done": true
      },
      {
        "name": "Random Country Generator",
        "slug": "random-country-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Lottery Number Generator",
        "slug": "lottery-number-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Random Emoji Generator",
        "slug": "random-emoji-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Wheel of Names Spinner",
        "slug": "wheel-of-names-spinner",
        "tier": 1,
        "done": true
      }
    ]
  },
  {
    "name": "Website & Network Tools",
    "slug": "website-and-network-tools",
    "tools": [
      {
        "name": "Ping Test",
        "slug": "ping-test",
        "tier": 5,
        "done": true
      },
      {
        "name": "DNS Lookup",
        "slug": "dns-lookup",
        "tier": 3,
        "done": true
      },
      {
        "name": "WHOIS Lookup",
        "slug": "whois-lookup",
        "tier": 5,
        "done": true
      },
      {
        "name": "IP Address Lookup",
        "slug": "ip-address-lookup",
        "tier": 2,
        "done": true
      },
      {
        "name": "My IP Address Finder",
        "slug": "my-ip-address-finder",
        "tier": 2,
        "done": true
      },
      {
        "name": "Website Speed Test",
        "slug": "website-speed-test",
        "tier": 5,
        "done": true
      },
      {
        "name": "HTTP Header Checker",
        "slug": "http-header-checker",
        "tier": 5,
        "done": true
      },
      {
        "name": "SSL Certificate Checker",
        "slug": "ssl-certificate-checker",
        "tier": 5,
        "done": true
      },
      {
        "name": "User Agent Detector",
        "slug": "user-agent-detector",
        "tier": 1,
        "done": true
      },
      {
        "name": "Website Screenshot Tool",
        "slug": "website-screenshot-tool",
        "tier": 5,
        "done": true
      },
      {
        "name": "Website Uptime Checker",
        "slug": "website-uptime-checker",
        "tier": 5,
        "done": true
      },
      {
        "name": "MX Record Lookup",
        "slug": "mx-record-lookup",
        "tier": 3,
        "done": true
      },
      {
        "name": "Subnet Calculator",
        "slug": "subnet-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "MAC Address Lookup Tool",
        "slug": "mac-address-lookup-tool",
        "tier": 2,
        "done": true
      }
    ]
  },
  {
    "name": "GIF & Meme Tools",
    "slug": "gif-and-meme-tools",
    "tools": [
      {
        "name": "GIF Maker from Video",
        "slug": "gif-maker-from-video",
        "tier": 4,
        "done": false
      },
      {
        "name": "GIF Maker from Images",
        "slug": "gif-maker-from-images",
        "tier": 3,
        "done": false
      },
      {
        "name": "GIF Resizer",
        "slug": "gif-resizer",
        "tier": 3,
        "done": false
      },
      {
        "name": "GIF Compressor",
        "slug": "gif-compressor",
        "tier": 4,
        "done": false
      },
      {
        "name": "GIF to Video Converter",
        "slug": "gif-to-video-converter",
        "tier": 4,
        "done": false
      },
      {
        "name": "GIF Splitter (Frame Extractor)",
        "slug": "gif-splitter",
        "tier": 3,
        "done": false
      },
      {
        "name": "GIF Speed Changer",
        "slug": "gif-speed-changer",
        "tier": 4,
        "done": false
      },
      {
        "name": "Reverse GIF Maker",
        "slug": "reverse-gif-maker",
        "tier": 4,
        "done": false
      },
      {
        "name": "Meme Caption Generator",
        "slug": "meme-caption-generator",
        "tier": 3,
        "done": false
      }
    ]
  },
  {
    "name": "Font & Typography Tools",
    "slug": "font-and-typography-tools",
    "tools": [
      {
        "name": "Fancy Text Generator",
        "slug": "fancy-text-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Typography Scale Generator",
        "slug": "typography-scale-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Font Pairing Generator",
        "slug": "font-pairing-generator",
        "tier": 2,
        "done": false
      },
      {
        "name": "Google Fonts Previewer",
        "slug": "google-fonts-previewer",
        "tier": 2,
        "done": false
      },
      {
        "name": "Font Identifier (Image to Font)",
        "slug": "font-identifier",
        "tier": 6,
        "done": false
      },
      {
        "name": "Font Format Converter (TTF/WOFF/OTF)",
        "slug": "font-format-converter",
        "tier": 4,
        "done": false
      }
    ]
  },
  {
    "name": "Writing & Citation Tools",
    "slug": "writing-and-citation-tools",
    "tools": [
      {
        "name": "Readability Score Checker",
        "slug": "readability-score-checker",
        "tier": 1,
        "done": true
      },
      {
        "name": "Citation Generator (APA/MLA/Chicago)",
        "slug": "citation-generator",
        "tier": 2,
        "done": false
      },
      {
        "name": "Plagiarism Checker",
        "slug": "plagiarism-checker",
        "tier": 6,
        "done": false
      },
      {
        "name": "Essay Outline Generator",
        "slug": "essay-outline-generator",
        "tier": 3,
        "done": false
      },
      {
        "name": "Bibliography Generator",
        "slug": "bibliography-generator",
        "tier": 2,
        "done": false
      },
      {
        "name": "Thesis Statement Generator",
        "slug": "thesis-statement-generator",
        "tier": 3,
        "done": false
      },
      {
        "name": "Grammar Checker",
        "slug": "grammar-checker",
        "tier": 6,
        "done": false
      }
    ]
  },
  {
    "name": "Email Tools",
    "slug": "email-tools",
    "tools": [
      {
        "name": "Email Validator",
        "slug": "email-validator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Email Address Extractor",
        "slug": "email-address-extractor",
        "tier": 1,
        "done": true
      },
      {
        "name": "Mail Header Analyzer",
        "slug": "mail-header-analyzer",
        "tier": 2,
        "done": false
      },
      {
        "name": "Email Signature Generator",
        "slug": "email-signature-generator",
        "tier": 2,
        "done": false
      },
      {
        "name": "Bulk Email List Verifier",
        "slug": "bulk-email-list-verifier",
        "tier": 5,
        "done": false
      },
      {
        "name": "Email Subject Line Tester",
        "slug": "email-subject-line-tester",
        "tier": 2,
        "done": false
      }
    ]
  },
  {
    "name": "Legal & Business Document Tools",
    "slug": "legal-and-business-document-tools",
    "tools": [
      {
        "name": "Privacy Policy Generator",
        "slug": "privacy-policy-generator",
        "tier": 2,
        "done": false
      },
      {
        "name": "Terms & Conditions Generator",
        "slug": "terms-and-conditions-generator",
        "tier": 2,
        "done": false
      },
      {
        "name": "NDA (Non-Disclosure Agreement) Generator",
        "slug": "nda-generator",
        "tier": 2,
        "done": false
      },
      {
        "name": "Disclaimer Generator",
        "slug": "disclaimer-generator",
        "tier": 2,
        "done": false
      },
      {
        "name": "Refund Policy Generator",
        "slug": "refund-policy-generator",
        "tier": 2,
        "done": false
      },
      {
        "name": "Cookie Policy Generator",
        "slug": "cookie-policy-generator",
        "tier": 2,
        "done": false
      },
      {
        "name": "Employment Contract Generator",
        "slug": "employment-contract-generator",
        "tier": 2,
        "done": false
      },
      {
        "name": "Rental/Lease Agreement Generator",
        "slug": "rental-lease-agreement-generator",
        "tier": 2,
        "done": false
      },
      {
        "name": "Freelance Contract Generator",
        "slug": "freelance-contract-generator",
        "tier": 2,
        "done": false
      },
      {
        "name": "Affidavit Template Generator",
        "slug": "affidavit-template-generator",
        "tier": 2,
        "done": false
      }
    ]
  },
  {
    "name": "Math Tools",
    "slug": "math-tools",
    "tools": [
      {
        "name": "Equation Solver",
        "slug": "equation-solver",
        "tier": 3,
        "done": true
      },
      {
        "name": "Quadratic Equation Solver",
        "slug": "quadratic-equation-solver",
        "tier": 1,
        "done": true
      },
      {
        "name": "Matrix Calculator",
        "slug": "matrix-calculator",
        "tier": 2,
        "done": true
      },
      {
        "name": "Graphing Calculator",
        "slug": "graphing-calculator",
        "tier": 3,
        "done": true
      },
      {
        "name": "Prime Number Checker",
        "slug": "prime-number-checker",
        "tier": 1,
        "done": true
      },
      {
        "name": "GCD & LCM Calculator",
        "slug": "gcd-and-lcm-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Factorial Calculator",
        "slug": "factorial-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Algebra Calculator",
        "slug": "algebra-calculator",
        "tier": 3,
        "done": true
      },
      {
        "name": "Trigonometry Calculator",
        "slug": "trigonometry-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Percentage Change Calculator",
        "slug": "percentage-change-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Number Rounding Tool",
        "slug": "number-rounding-tool",
        "tier": 1,
        "done": true
      }
    ]
  },
  {
    "name": "Language & Translation Tools",
    "slug": "language-and-translation-tools",
    "tools": [
      {
        "name": "Language Translator",
        "slug": "language-translator",
        "tier": 5,
        "done": false
      },
      {
        "name": "Language Detector",
        "slug": "language-detector",
        "tier": 3,
        "done": false
      },
      {
        "name": "Dictionary Lookup",
        "slug": "dictionary-lookup",
        "tier": 3,
        "done": false
      },
      {
        "name": "Thesaurus / Synonym Finder",
        "slug": "thesaurus-synonym-finder",
        "tier": 3,
        "done": false
      },
      {
        "name": "Text Pronunciation Guide",
        "slug": "text-pronunciation-guide",
        "tier": 3,
        "done": false
      },
      {
        "name": "Word Definition Lookup",
        "slug": "word-definition-lookup",
        "tier": 3,
        "done": false
      }
    ]
  },
  {
    "name": "Crypto & Currency Tools",
    "slug": "crypto-and-currency-tools",
    "tools": [
      {
        "name": "Cryptocurrency Price Converter",
        "slug": "cryptocurrency-price-converter",
        "tier": 3,
        "done": true
      },
      {
        "name": "Bitcoin Address Validator",
        "slug": "bitcoin-address-validator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Crypto Wallet Address QR Generator",
        "slug": "crypto-wallet-address-qr-generator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Mining Profitability Calculator",
        "slug": "mining-profitability-calculator",
        "tier": 3,
        "done": true
      },
      {
        "name": "Live Currency Exchange Rate Checker",
        "slug": "live-currency-exchange-rate-checker",
        "tier": 3,
        "done": true
      }
    ]
  },
  {
    "name": "Signature Tools",
    "slug": "signature-tools",
    "tools": [
      {
        "name": "Digital Signature Maker",
        "slug": "digital-signature-maker",
        "tier": 2,
        "done": false
      },
      {
        "name": "Handwritten Signature Generator",
        "slug": "handwritten-signature-generator",
        "tier": 2,
        "done": false
      },
      {
        "name": "Signature to Transparent PNG Converter",
        "slug": "signature-to-transparent-png-converter",
        "tier": 2,
        "done": false
      },
      {
        "name": "Initials Logo Generator",
        "slug": "initials-logo-generator",
        "tier": 2,
        "done": false
      }
    ]
  },
  {
    "name": "Time & Productivity Tools",
    "slug": "time-and-productivity-tools",
    "tools": [
      {
        "name": "World Clock",
        "slug": "world-clock",
        "tier": 1,
        "done": true
      },
      {
        "name": "Pomodoro Timer",
        "slug": "pomodoro-timer",
        "tier": 1,
        "done": true
      },
      {
        "name": "Online Stopwatch",
        "slug": "online-stopwatch",
        "tier": 1,
        "done": true
      },
      {
        "name": "Countdown to Date Widget",
        "slug": "countdown-to-date-widget",
        "tier": 1,
        "done": true
      },
      {
        "name": "Work Days Calculator",
        "slug": "work-days-calculator",
        "tier": 1,
        "done": true
      },
      {
        "name": "Meeting Time Planner (Time Zone Overlap)",
        "slug": "meeting-time-planner",
        "tier": 2,
        "done": false
      },
      {
        "name": "Habit Tracker Sheet Generator",
        "slug": "habit-tracker-sheet-generator",
        "tier": 2,
        "done": false
      }
    ]
  },
  {
    "name": "Education Tools",
    "slug": "education-tools",
    "tools": [
      {
        "name": "Flashcard Maker",
        "slug": "flashcard-maker",
        "tier": 2,
        "done": false
      },
      {
        "name": "Quiz Generator",
        "slug": "quiz-generator",
        "tier": 2,
        "done": false
      },
      {
        "name": "Multiple Choice Test Generator",
        "slug": "multiple-choice-test-generator",
        "tier": 2,
        "done": false
      },
      {
        "name": "Handwriting Practice Sheet Generator",
        "slug": "handwriting-practice-sheet-generator",
        "tier": 3,
        "done": false
      },
      {
        "name": "Graph Paper Generator",
        "slug": "graph-paper-generator",
        "tier": 2,
        "done": false
      },
      {
        "name": "Timetable / Schedule Generator",
        "slug": "timetable-schedule-generator",
        "tier": 2,
        "done": false
      }
    ]
  },
  {
    "name": "Presentation Tools",
    "slug": "presentation-tools",
    "tools": [
      {
        "name": "PPT to Video Converter",
        "slug": "ppt-to-video-converter",
        "tier": 6,
        "done": false
      },
      {
        "name": "PPT to Images",
        "slug": "ppt-to-images",
        "tier": 5,
        "done": false
      },
      {
        "name": "Slide Background Remover",
        "slug": "slide-background-remover",
        "tier": 5,
        "done": false
      },
      {
        "name": "Presentation Template Generator",
        "slug": "presentation-template-generator",
        "tier": 3,
        "done": false
      },
      {
        "name": "Slide Text Extractor",
        "slug": "slide-text-extractor",
        "tier": 2,
        "done": false
      }
    ]
  }
];

const seenSlugs = new Set<string>();
export const ALL_TOOLS: (Tool & { categoryName: string; categorySlug: string })[] =
  TOOL_CATEGORIES.flatMap((category) =>
    category.tools.map((tool) => ({
      ...tool,
      categoryName: category.name,
      categorySlug: category.slug,
    }))
  ).filter((tool) => {
    if (seenSlugs.has(tool.slug)) return false;
    seenSlugs.add(tool.slug);
    return true;
  });

export const TOTAL_TOOLS = 574;
export const TOTAL_TOOLS_DONE = 423;
