import type { ToolContent } from "./types";

export const textToSpeechContent: ToolContent = {
  heroSubtitle: "Convert Text to Natural-Sounding Speech, Free",
  overview: [
    "Text-to-speech is useful far beyond accessibility — proofreading an article by listening to it (mistakes are often easier to catch by ear than by eye), previewing how a script or voiceover will sound before recording it for real, or simply having something read aloud while doing something else. Most text-to-speech tools online require an account, a per-character fee, or an upload to a server, when modern browsers already have a capable speech engine built in.",
    "This tool uses the Web Speech API's speech synthesis feature, which is built directly into Chrome, Edge, and Safari — no account, no upload, no character limit imposed by this tool. Type or paste any text, pick from the voices your operating system and browser provide (which typically include several languages and both male and female voices), adjust the playback speed, and press play to hear it read aloud immediately.",
    "Because the voices come from your browser and operating system rather than from this tool, voice quality and the exact list of available voices varies by device — a Mac, Windows PC, and Android phone will each offer a somewhat different voice lineup, all in the same browser. There's no server round-trip involved at any point: your text never leaves your device, and speech is generated by your machine's own text-to-speech engine.",
  ],
  howItWorks: [
    { title: "Type or paste text", description: "Enter the text you want read aloud." },
    { title: "Pick a voice and speed", description: "Choose from your device's available voices and adjust the playback rate." },
    { title: "Press Speak", description: "Your browser reads the text aloud immediately, using its built-in speech engine." },
  ],
  examples: [
    {
      label: "Basic usage",
      input: "\"Welcome to Toolspica.\" at 1.0x speed",
      output: "Spoken aloud through your device's speakers using the selected voice.",
    },
  ],
  faqs: [
    {
      question: "Why do I see a different list of voices than someone on another device?",
      answer:
        "Voices come from your operating system and browser, not from this tool — Windows, macOS, iOS, and Android each ship with a different set of built-in voices, so the exact list you see depends on your device.",
    },
    {
      question: "Is there a character limit on how much text I can convert?",
      answer:
        "This tool doesn't impose one — very long text may take a while to finish reading aloud, but there's no artificial cutoff on input length.",
    },
    {
      question: "Can I download the speech as an audio file?",
      answer:
        "Not with this tool — it plays audio live through your browser's speech engine rather than producing a downloadable file, since browsers don't provide a direct way to capture synthesized speech as an exportable clip.",
    },
    {
      question: "Is my text sent to a server to generate speech?",
      answer:
        "No — speech synthesis happens entirely on your device using your browser's built-in Web Speech API. Nothing you type is uploaded anywhere.",
    },
  ],
};
