import type { ToolContent } from "./types";

export const xmlFormatterContent: ToolContent = {
  heroSubtitle: "Pretty-Print Minified or Messy XML With Proper Indentation",
  overview: [
    "XML that's been minified, generated by an API, or pasted from a log file often arrives as one dense unreadable line — impossible to actually review or debug without reformatting it first. This tool validates your XML and reformats it with consistent two-space indentation, making the document's nesting structure immediately readable.",
    "Validation happens via the browser's built-in DOMParser before formatting, so malformed XML is caught and flagged with a clear error rather than silently producing broken output. Once validated, the tool walks the tag structure and rebuilds it with proper indentation reflecting each element's nesting depth.",
    "This is a common step when debugging an API response, reviewing a configuration file, or just making sense of XML data that's been stripped of whitespace for transmission efficiency — reformatting it back to readable structure takes one paste.",
  ],
  howItWorks: [
    { title: "Paste your XML", description: "Minified, single-line, or otherwise unformatted." },
    { title: "Validation runs automatically", description: "Malformed XML is flagged with a clear error." },
    { title: "Copy the formatted result", description: "Properly indented, readable XML." },
  ],
  examples: [
    { label: "Formatting a minified API response", input: "<root><item id=\"1\">Hello</item></root>", output: "Indented, multi-line XML with clear nesting" },
  ],
  faqs: [
    { question: "Does this validate my XML is well-formed?", answer: "Yes — it uses the browser's built-in XML parser, so malformed XML is caught and reported before formatting." },
    { question: "Does it handle XML namespaces?", answer: "Yes — namespace prefixes and declarations are preserved as-is through formatting." },
    { question: "What about XML declarations and comments?", answer: "XML declarations (<?xml ...?>) are preserved on their own line; standard XML comments pass through unchanged." },
    { question: "Is my XML uploaded anywhere?", answer: "No — parsing and formatting run entirely in your browser." },
    { question: "Does this validate against a schema (XSD)?", answer: "No — it checks that the XML is well-formed, not that it conforms to a specific schema." },
  ],
};
